apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandraclusters.database.pantheon.io
spec:
  group: database.pantheon.io
  names:
    kind: CassandraCluster
    listKind: CassandraClusterList
    plural: cassandraclusters
    singular: cassandracluster
  # TODO: Uncomment when we upgrade to 1.11 kube
  # additionalPrinterColumns:
  # - name: Size
  #   type: integer
  #   description: Number of nodes in the cluster
  #   JSONPath: .spec.size
  # - name: Status
  #   type: string
  #   description: cluster status
  #   JSONPath: .status.phase
  # - name: Image
  #   type: string
  #   description: image nodes are using
  #   JSONPath: .spec.image
  scope: Namespaced
  version: v1alpha1
validation:
  openAPIV3Schema:
    properties:
      spec:
        properties:
          size:
            description: number of nodes in cluster
            type: integer
            required: true
            minimum: 1
          enablePublicPodServices:
            description: enables public services for each individual pod (node)
            type: boolean
          repair:
            properties:
              schedule:
                description: schedule for full cluster repair in cron format
                type: string
                pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
              image:
                description: repair job image to execute
                type: string
          node:
            properties:
              persistentVolume:
                properties:
                  storageClass:
                    description: PV storage class
                    type: string
                    enum:
                    - ssd
                    - standard
              image:
                description: cassandra node image to use
                type: string
          keyspaceName:
            description: name of primary keyspace for cluster, defaults to cluster-name
            type: string
          secretName:
            description: name of kube secret resource for cassandra certificates
            type: string
          configMapName:
            description: name of kube configmap resource for cassandra.yaml
            type: string
          jvmAgentConfigName:
            description: name of kube configmap resource for jolokia agent
            type: string
          jvmAgent:
            description: type of jmx/jvm agent to use (sidecar or jvm)
            type: string
            enum:
            - sidecar
            - jvm
          datacenter:
            description: name of datacenter (defaults to region name in cloud)
            type: string
          externalSeeds:
            description: comma separated list of external seeds for multi-dc
            type: string
          
            

